import {ArticleCatalogList} from "../types/article";

export const links: ArticleCatalogList = [
    {
        name: "Social",
        id: "972",
        company_id: [],
        variant: "ghost",
        article_collect_ids: [1, 2, 3],
    },
    {
        name: "Updates",
        id: "342",
        company_id: [],
        variant: "ghost",
        article_collect_ids: [4, 5, 6],
    },
    {
        name: "Forums",
        id: "128",
        company_id: [],
        variant: "ghost",
        article_collect_ids: [7, 8, 9, 10],
    },
    {
        name: "Shopping",
        id: "8",
        company_id: [],
        variant: "ghost",
        article_collect_ids: [11],
    },
    {
        name: "Promotions",
        id: "21",
        company_id: [],
        variant: "ghost",
        article_collect_ids: []
    },
    {
        name: "Social",
        id: "972",
        company_id: [],
        variant: "ghost",
        article_collect_ids: [1, 2, 3],
    },
    {
        name: "Updates",
        id: "342",
        company_id: [],
        variant: "ghost",
        article_collect_ids: [4, 5, 6, 32, 33],
    },
    {
        name: "Forums",
        id: "128",
        company_id: [],
        variant: "ghost",
        article_collect_ids: [7, 8, 9, 10],
    },
    {
        name: "Shopping",
        id: "8",
        company_id: [],
        variant: "ghost",
        article_collect_ids: [11],
    },
    {
        name: "Promotions",
        id: "21",
        company_id: [],
        variant: "ghost",
        article_collect_ids: []
    },
    {
        name: "Social",
        id: "972",
        company_id: [],
        variant: "ghost",
        article_collect_ids: [1, 2, 3],
    },
    {
        name: "Updates",
        id: "342",
        company_id: [],
        variant: "ghost",
        article_collect_ids: [4, 5, 6, 32, 33],
    },
    {
        name: "Forums",
        id: "128",
        company_id: [],
        variant: "ghost",
        article_collect_ids: [7, 8, 9, 10],
    },
    {
        name: "Shopping",
        id: "8",
        company_id: [],
        variant: "ghost",
        article_collect_ids: [11],
    },
    {
        name: "Promotions",
        id: "21",
        company_id: [],
        variant: "ghost",
        article_collect_ids: []
    }
];

export const articleCollects = [
    {
        id: "1",
        name: "ArticleCollect 1",
        description: "This is a description",
        category_id: "1",
        article_ids: ["1", "2"],
        company_id: "1",
        active: true,
        update_at: "2023-09-01",
    },
    {
        id: "2",
        name: "ArticleCollect 2",
        description: "This is a description",
        category_id: "1",
        article_ids: ["1", "2"],
        company_id: "1",
        active: true,
        update_at: "2023-11-01",
    },
    {
        id: "3",
        name: "ArticleCollect 3",
        description: "This is a description",
        category_id: "1",
        article_ids: ["1", "2"],
        company_id: "1",
        active: true,
        update_at: "2024-01-01",
    },
    {
        id: "4",
        name: "ArticleCollect 4",
        description: "This is a description",
        category_id: "1",
        article_ids: ["1", "2"],
        company_id: "1",
        active: true,
        update_at: "2023-12-05",
    },
    {
        id: "5",
        name: "ArticleCollect 5",
        description: "This is a description",
        category_id: "1",
        article_ids: ["1", "2"],
        company_id: "1",
        active: false,
        update_at: "2021-09-01",
    },
    {
        id: "6",
        name: "ArticleCollect 6",
        description: "This is a description",
        category_id: "1",
        article_ids: ["1", "2"],
        company_id: "1",
        active: true,
        update_at: "2021-09-01",
    },
    {
        id: "7",
        name: "ArticleCollect 7",
        description: "This is a description",
        category_id: "1",
        article_ids: ["1", "2"],
        company_id: "1",
        active: false,
        update_at: "2021-09-01",
    },
    {
        id: "8",
        name: "ArticleCollect 8",
        description: "This is a description",
        category_id: "1",
        article_ids: ["1", "2"],
        company_id: "1",
        active: true,
        update_at: "2021-09-01",
    },
];
